name: Bug Report
description: Use this form to submit a bug report.
title: "Bug Report - [DATE]: [BUG SUMMARY]"
labels: [ "bug" ]
body:
  - type: input
    id: browserName
    attributes:
      label: Browser Name
      description: What browser are you using?
      placeholder: "Example: Firefox"
    validations:
      required: true
  - type: input
    id: browserVersion
    attributes:
      label: Browser Version
      description: What version of your browser are you using?
      placeholder: "Example: v121.0"
    validations:
      required: false
  - type: checkboxes
    attributes:
      label: Code of Conduct
      description: The Code of Conduct helps create a safe space for everyone. We require that everyone agrees to it.
      options:
        - label: "I agree to follow this project's [Code of Conduct](https://github.com/brittni-and-the-polar-bear/.github/tree/main?tab=coc-ov-file#readme)."
          required: true
  - type: textarea
    attributes:
      label: Issue Description
      description: Please explain in detail the problems you are experiencing with the program.
    validations:
      required: true
  - type: markdown
    attributes:
      value: "## Thank you for your feedback!"
